version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/bot'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/dashboard'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/database'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/utils'
    schedule:
      interval: 'weekly'
